---
- name: Backup VMs
  ansible.posix.synchronize:
    src: /var/lib/libvirt/images
    dest: /net/backup/servers/darknet/
    compress: no
    delete: yes
    rsync_opts:
      - "--include {{item}}-disk1"
      - "--include {{item}}-disk2"
      - "--include {{item}}.qcow2"
      - "--exclude '*'"
      - "--sparse"
  when:
    - nodes.list_vms is defined
    - item not in (skip_backup | default(''))
  with_items: "{{nodes.list_vms}}"
  delegate_to: "{{ inventory_hostname }}"
  tags: backup

- name: Backup VMs config
  copy:
    remote_src: yes
    src: "/etc/libvirt/qemu/{{ item }}.xml"
    dest: "/net/backup/servers/darknet/{{ item }}.xml"
  when:
    - nodes.list_vms is defined
  with_items: "{{nodes.list_vms}}"
  tags: backup
