---
- name: Find disk images
  ansible.builtin.find:
    paths: /var/lib/libvirt/images
    patterns: "{{item}}-disk1,{{item}}-disk2,{{item}}.qcow2"
  register: disk_image
  when:
    - nodes.list_vms is defined
    - item not in (skip_backup | default(''))
  with_items: "{{nodes.list_vms}}"
  tags: backup


- name: Create image list
  set_fact:
    image_files: "{{ image_files | default([]) + disk_image.results | selectattr('item', 'equalto', item) | map(attribute='files') | list }}"
  when:
    - nodes.list_vms is defined
    - item not in (skip_backup | default(''))
  with_items: "{{nodes.list_vms}}"


- name: Backup VMs
  ansible.posix.synchronize:
    src: "{{item.path}}"
    dest: /net/backup/servers/darknet/
    compress: no
#    checksum: yes
    rsync_opts:
      - "--sparse"
#      - "--dry-run"
  with_items: "{{image_files}}"
  delegate_to: "{{ inventory_hostname }}"
  tags: backup
  loop_control:
    label: "{{ item.path }}"
  ignore_errors: yes


- name: Backup VMs config
  copy:
    remote_src: yes
#    checksum: yes
    src: "/etc/libvirt/qemu/{{ item }}.xml"
    dest: "/net/backup/servers/darknet/{{ item }}.xml"
  when:
    - nodes.list_vms is defined
  with_items: "{{nodes.list_vms}}"
  tags: backup
