---
- name: Find nodes on controller
  community.libvirt.virt:
    command: list_vms
  register: nodes
  tags: always

- name: Get node info
  community.libvirt.virt:
    command: info
  register: virt_info
  tags: always

- name: Set libvirt facts
  set_fact:
    nodes: "{{ nodes }}"
    virt_info: "{{ virt_info }}"
  tags: always
